doctrine:
    dbal:
        dbname: '%env(DATABASE_DBNAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: '%env(DATABASE_DRIVER)%'
        types:
          
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Device:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/BackOffice/Devices/Infrastructure/Persistence/Doctrine'
                prefix: 'Vic\BackOffice\Devices\Domain'
                alias: Vic\BackOffice\Devices\Domain
            