devices_put:
  path: api/devices/{id}
  controller: App\Controller\Devices\DevicesPutController
  methods: PUT

devices_get:
  path: api/devices/{id}
  controller: App\Controller\Devices\DevicesGettController
  methods: GET